version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18.x

  build:
    commands:
      - echo "install Node.js dependencies"
      - mkdir dep
      - npm install log4js --prefix ./dep

  post_build:
    commands:
      - aws cloudformation package --template-file function.yml --s3-bucket $S3BUCKET --output-template-file function-out.yml

artifacts:
  type: zip
  files:
    - function-out.yml
