version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18.x
  build:
    commands:
      - echo "install Node.js dependencies"
      - npm install log4js 
  post_build:
    commands:
      - aws cloudformation package --template-file function.yml --s3-bucket $S3BUCKET --force-upload --output-template-file function-out.yml
artifacts:
  type: zip
  files:
    - function.yml
    - function-out.yml # Use this template for Deploy stage
